<?php
define('DEBUG', TRUE);
//define('DEBUG', FAlSE);
define("LEGAL", TRUE);
define('ROOT', dirname(__FILE__).'/');

//0 --- no log
//1 --- sql log
//2 --- fatal errors 
define("LOG_LEVEL", 2);
define("APPDIR", ROOT."app/");
define("DATADIR", ROOT."data/");
define("LIBDIR", ROOT."lib/");
define("TPLDIR", ROOT."tpl/");
define("CONFDIR", ROOT."conf/");




//user define
define("WEB_URL", "http://wxd.dangdang.com/");
