<?php defined('UNION') OR die('Acess deny!');?>
</div>
<div class="clear"></div>
<!--页尾 开始 -->
<link type="text/css" rel="stylesheet" href="http://static.dangdang.com/css/public_footer090310.css">
<div class="public_footer_add_s"></div>
    <div class="public_footer">
        <div class="public_footer_list1">
            <div class="public_footer_title">新手上路</div>
            <div class="public_footer_info">
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1978/9210.shtml">新用户注册</a><br>
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1978/9209.shtml">怎样下订单</a><br>
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1980/9215.shtml">会员积分计划</a><br>
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1978/10893.shtml">发票制度</a>
            </div>
        </div>
        <div class="public_footer_list1">
            <div class="public_footer_title">付款方式</div>
            <div class="public_footer_info">
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1982/9516.shtml">支付方式</a><br>
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1975/9196.shtml">网上支付常见问题</a><br>
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1982/17104.shtml">汇款单招领</a><br>
                <a class="public_footer_black_404040" target="_blank" href="http://order.dangdang.com/mymoney.aspx">激活礼品卡</a><br>
            </div>
        </div>
        <div class="public_footer_list1">
            <div class="public_footer_title">配送服务</div>
            <div class="public_footer_info">
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/topic/744/200973/14253.shtml">配送范围/时间/运费</a>
            </div>
        </div>
        <div class="public_footer_list1">
            <div class="public_footer_title">售后服务</div>
            <div class="public_footer_info">
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1988/9251.shtml">服务保障承诺</a><br>
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1985/9240.shtml">退换货政策</a><br>
                <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1985/9238.shtml">退换货流程</a><br>
                <a class="public_footer_black_404040" target="_blank" href="http://order.dangdang.com/return/return_start.aspx">退货申请</a><br><!--09-04-28zhangliang edit-->
                <a class="public_footer_black_404040" target="_blank" href="http://order.dangdang.com/return/exchange_start.aspx">换货申请</a>
            </div>
        </div>
        <div class="public_footer_list2">
        <div class="public_footer_title">帮助中心</div>
        <div class="public_footer_info">
            <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/">常见热点问题</a><br>
            <a class="public_footer_black_404040" target="_blank" href="http://static.dangdang.com/helpcenter2/1978/11069.shtml">找回密码</a><br>
            <a class="public_footer_black_404040" target="_blank" href="http://misc.dangdang.com/help/customer_complaining.asp">顾客建议</a>
        </div>
    </div>
    <div class="public_footer_bottom">
        <div class="public_footer_red">
            <a target="_blank" href="http://static.dangdang.com/topic/other/profile.shtml">公司简介</a>　　|　　<a target="_blank" href="http://static.dangdang.com/topic/contents/1119/2263.html">诚征英才</a>　　|　　<a target="_blank" href="http://union.dangdang.com/">网站联盟</a>　　|　　<a target="_blank" href="http://static.dangdang.com/topic/744/2008326/8251.shtml">百货招商</a>　　|　　<a target="_blank" href="http://misc.dangdang.com/groupbuy/Default.aspx">团购</a>　　|　<a target="_blank" href="http://static.dangdang.com/helpcenter2/1988/9251.shtml">交易条款</a>
        </div>
        <div style="line-height: 48px;" class="public_footer_icp">Copyright (C) 当当网 2004-2010, All Rights Reserved                  <a target="_blank" href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098"><img border="0" align="middle" src="http://img4.dangdang.com/bottom/validate.gif"></a> <a style="color: rgb(102, 102, 102);" target="_blank" href="http://www.miibeian.gov.cn/">京ICP证041189号</a> <a style="color: rgb(102, 102, 102);" target="_blank" href="http://static.dangdang.com//music/topic/847_10762.shtml">音像制品经营许可证 京音网8号</a>
        </div>
    </div>
</div>
<script src="http://central.dangdang.com/js/o_code.js" language="javascript"></script>
<script src="http://central.dangdang.com/js/trace.js" language="javascript"></script>
</div>