<style type="text/css" title="">
/*footer*/
.public_footer_box,.public_footer_box3{ width:960px; margin:0 auto; background:#f9f9f9 url(http://img4.ddimg.cn/header/header2010/bg_footer_0826.gif) repeat-x 0 -150px; padding:20px 0 35px; font:12px "宋体",Arial,Helvetica,sans-serif; clear:both;}
.public_footer{ margin:0 auto; width:950px; padding:32px 5px 0; background:#f9f9f9 url(http://img4.ddimg.cn/header/header2010/bg_footer_0826.gif) repeat-x 0 -170px; font:12px; color:#666; overflow:hidden;}
.public_footer_box3{ background-color:#fff; width:960px; margin:0 auto;}
.public_footer_box3 .public_footer{ background-color:#fff;}

.public_footer a{ color:#666!important; text-decoration:none; font-size:12px;}
.public_footer a:hover{ color:#f60!important; text-decoration:underline;}

.public_footer .footer_sort{ width:137px; padding:0 24px 0 1px; display:block; float:left;}
.public_footer .footer_help{ padding-right:0;}
.public_footer .footer_sort h2{ font-size:0; border-bottom:1px solid #dcdcdc; height:22px; line-height:0; font-size:0; overflow:hidden; text-indent:-9999px; width:137px; background:url(http://img4.ddimg.cn/header/header2010/icon_footer.gif) no-repeat 14px 0;}
.public_footer .footer_sort ul{ display:block; padding:7px 0 0 0;}
.public_footer .footer_sort ul li{ padding-left:30px; background:url(http://img4.ddimg.cn/header/header2010/icon_footer.gif) no-repeat 17px -177px; height:20px; line-height:20px;} /*gy 100730 修改*/

.public_footer .footer_nav{ text-align:center; margin:0 0 12px; }/*gy 100730 修改*/
.public_footer .footer_nav span{ display:inline-block; padding:0 18px;}/*gy 100730 修改*/
.public_footer .footer_copyright{ padding-left:168px; margin:0 auto; width:792px; }/*gy 100730 修改*/
.public_footer .footer_copyright span,.public_footer .footer_copyright a.footer_img{ display:block; float:left;}
.public_footer .footer_copyright span{ padding-top:19px;}
.public_footer .footer_copyright a{ padding:0 4px;}
.public_footer .footer_copyright a.footer_img{ padding-right:0;}
</style>
<div class="public_footer_box">
  <div class="public_footer">
    <div class="footer_nav"><a href="http://static.dangdang.com/topic/2227/176801.shtml" target="_blank">公司简介</a><span>|</span><a href="http://static.dangdang.com/topic/contents/1119/2263.shtml" target="_blank">诚征英才</a><span>|</span><a href="http://union.dangdang.com" target="_blank">网站联盟</a><span>|</span><a href="http://static.dangdang.com/topic/744/8251.shtml" target="_blank">百货招商</a><span>|</span><a href="http://misc.dangdang.com/groupbuy/Default.aspx" target="_blank">团购</a><span>|</span><a href="http://support.dangdang.com/helpcenter/api_cms/helpcenter/question_sort/2239/180087.shtml" target="_blank">手机当当</a><span>|</span><a href="http://blog.dangdang.com/" target="_blank">官方Blog</a></div>
    <div class="footer_copyright"><span>Copyright (C) 当当网 2004-2010, All Rights Reserved</span><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img"><img src="<?=WEB_URL?>img/validate.gif" /></a><span><a href="http://www.miibeian.gov.cn/" target="_blank">京ICP证041189号</a></span><span><a href="http://static.dangdang.com//music/topic/847_10762.shtml" target="_blank">音像制品经营许可证 京音网8号</a></span></div>
  </div>
</div>