<div class="union_head">
    <div class="head_bord">
        <div class="head_back">[<a target="_blank" href="http://www.dangdang.com">回当当网首页</a>]</div>
        <a target="_blank" href="<?=WEB_ROOT?>"><img border="0" title="当当联盟" class="logo_union" src="<?=WEB_URL?>img/logo_union.gif"></a>
        <div class="union_head_nav">
            <div class="union_head_nav_f"><span class="gray666"><a target="_blank" href="http://static.dangdang.com/union/contents/2085/11514.shtml">联盟指南</a></span></div>
            <div class="union_head_nav_f"><span class="gray666"><a target="_blank" href="http://static.dangdang.com/union/contents/2085/11269.shtml">联盟协议</a></span></div>
            <div class="union_head_nav_f"><span class="gray666"><a target="_blank" href="http://static.dangdang.com/union/contents/2085/11515.shtml">常见问题</a></span></div>
        </div>
    </div>
</div>
